server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/build;
        index index.html index.htm index.nginx-debian.html;

        server_name mineswepperdm151708.ru www.mineswepperdm151708.ru;

        location / {
                try_files $uri $uri/ =404;
        }
}
server {
        root /var/www/build;
        index index.html index.htm index.nginx-debian.html;
        server_name mineswepperdm151708.ru; # managed by Certbot
        location / {
                try_files $uri $uri/ =404;
        }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/mineswepperdm151708.ru/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/mineswepperdm151708.ru/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = mineswepperdm151708.ru) {
        return 301 https://$host$request_uri;
    }
        listen 80 ;
        listen [::]:80 ;
    server_name mineswepperdm151708.ru;
    return 404;
}